import random
from typing import List

############### Cyclic groups (finite) #######################

class CyclicGroup:
    """
    Finite cyclic group of order n, isomorphic to Z/nZ under addition.

    The cyclic group of order n is generated by a single element g where g^n = e
    (the identity). Elements are represented as integers 0, 1, ..., n-1, with
    composition given by addition modulo n.

    Parameters
    ----------
    order : int
        The order of the cyclic group (positive integer).

    Notes
    -----
    For continuous rotations, use CircleGroup (angles in [0, 2π)).

    """
    abelian = True

    def __init__(self, order: int):
        if not isinstance(order, int) or order <= 0:
            raise ValueError(f"Order must be a positive integer, got {order}")
        self.order = order

    def enumerate_elements(self) -> List[int]:
        """Enumerate all elements in the group.

        Returns
        -------
        List[int]
            List of all group elements [0, 1, ..., n-1].
        """
        return list(range(self.order))

    def sample(self) -> int:
        """Sample a random element of the cyclic group.

        Returns
        -------
        int
            Random integer from {0, 1, ..., n-1}.
        """
        return random.randrange(self.order)

    def compose(self, g1: int, g2: int) -> int:
        """Compose two group elements via addition modulo n.

        Parameters
        ----------
        g1 : int
            First group element.
        g2 : int
            Second group element.

        Returns
        -------
        int
            The composition (g1 + g2) mod n.
        """
        return (g1 + g2) % self.order

    def inverse(self, g: int) -> int:
        """Compute the inverse of a group element.

        Parameters
        ----------
        g : int
            Group element.

        Returns
        -------
        int
            The inverse element such that compose(g, inverse(g)) = identity().
        """
        return (self.order - g) % self.order

    def identity(self) -> int:
        """Return the identity element.

        Returns
        -------
        int
            The identity element (0).
        """
        return 0
    
